<HTML>
<HEAD>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<TITLE>PHPによるメール送信</TITLE>
</HEAD>
<BODY>



<?php
  
  // 文字コードを設定
  mb_language("Japanese");
  mb_internal_encoding("SHIFT-JIS");
  
  
  $to = "okazaki@prc.tsukuba.ac.jp";
  $subject = "*TEST* PHPによるメール送信";
  $header = "From: " . "okazaki@prc.tsukuba.ac.jp";                    // ########
  
  $body = "This is a test mail generated by PHP\n";
  $body .= "\n これはPHPで作成されたメールです。\n";
  $body .= "\nBest regards,";
  
  
  //メール送信の実行
  if(mb_send_mail($to,$subject,$body,$header)) {
    $_msg = "Sucessed!";
  } else {
    $_msg = "Faile in mail sending";
  }
  
  echo date('H:i:s')."  メール送信終了 (".$_msg.")<br>";
  
?>



</BODY>
</HTML>
